package edu.scu.corpmap.entity.mysql;

public class HotCorp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_corp.id
     *
     * @mbg.generated Wed Jun 20 20:03:33 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_corp.name
     *
     * @mbg.generated Wed Jun 20 20:03:33 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_corp.count
     *
     * @mbg.generated Wed Jun 20 20:03:33 CST 2018
     */
    private Long count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_corp.id
     *
     * @return the value of hot_corp.id
     *
     * @mbg.generated Wed Jun 20 20:03:33 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_corp.id
     *
     * @param id the value for hot_corp.id
     *
     * @mbg.generated Wed Jun 20 20:03:33 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_corp.name
     *
     * @return the value of hot_corp.name
     *
     * @mbg.generated Wed Jun 20 20:03:33 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_corp.name
     *
     * @param name the value for hot_corp.name
     *
     * @mbg.generated Wed Jun 20 20:03:33 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_corp.count
     *
     * @return the value of hot_corp.count
     *
     * @mbg.generated Wed Jun 20 20:03:33 CST 2018
     */
    public Long getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_corp.count
     *
     * @param count the value for hot_corp.count
     *
     * @mbg.generated Wed Jun 20 20:03:33 CST 2018
     */
    public void setCount(Long count) {
        this.count = count;
    }
}