package edu.scu.corpmap.entity.mysql;

import java.util.Date;

public class NewsDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.id
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.title
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.preview_image
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    private String previewImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.time
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_detail.content
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.id
     *
     * @return the value of news_detail.id
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.id
     *
     * @param id the value for news_detail.id
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.title
     *
     * @return the value of news_detail.title
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.title
     *
     * @param title the value for news_detail.title
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.preview_image
     *
     * @return the value of news_detail.preview_image
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    public String getPreviewImage() {
        return previewImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.preview_image
     *
     * @param previewImage the value for news_detail.preview_image
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    public void setPreviewImage(String previewImage) {
        this.previewImage = previewImage == null ? null : previewImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.time
     *
     * @return the value of news_detail.time
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.time
     *
     * @param time the value for news_detail.time
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_detail.content
     *
     * @return the value of news_detail.content
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_detail.content
     *
     * @param content the value for news_detail.content
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}