package edu.scu.corpmap.dao;

import edu.scu.corpmap.entity.mysql.NewsDetail;
import edu.scu.corpmap.entity.mysql.NewsDetailExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface NewsDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    long countByExample(NewsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    int deleteByExample(NewsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    int insert(NewsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    int insertSelective(NewsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    List<NewsDetail> selectByExampleWithBLOBs(NewsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    List<NewsDetail> selectByExample(NewsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    NewsDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") NewsDetail record, @Param("example") NewsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NewsDetail record, @Param("example") NewsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    int updateByExample(@Param("record") NewsDetail record, @Param("example") NewsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    int updateByPrimaryKeySelective(NewsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(NewsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_detail
     *
     * @mbg.generated Mon Jul 23 15:09:54 CST 2018
     */
    int updateByPrimaryKey(NewsDetail record);

    /**
     * This method was created by VicentChen
     * This method corresponds to using LIMIT
     *
     * Fri July 23 15:13:33 CST 2018
     */
    List<NewsDetail> selectByExampleUsingLimit(NewsDetailExample example);
}